language: node_js
node_js:
  - "10"
script:
  - npm run release

deploy:
  provider: npm
  emial: "$U_EMAIL"
  api_key: "$NPM_TOKEN"

branches:
  only:
    - master

notifications:
  email:
    - "$U_EMAIL"
  on_failure: always
