language: node_js
node_js:
  - "10"
script:
  - npm run release

deploy:
  provider: npm
  emial: jermken@163.com
  api_key: "53aee724-baae-42b4-9646-1382f36fbfd6"

branches:
  only:
    - master

notifications:
  email:
    - jermken@163.com
  on_failure: always
